# Generated by Django 5.1.2 on 2024-12-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaventa', models.DateField()),
                ('idcliente', models.IntegerField()),
                ('idempleado', models.IntegerField()),
                ('listaproducto', models.TextField(max_length=500)),
                ('totalventa', models.IntegerField()),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
