# Generated by Django 5.1.2 on 2024-12-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('correoelectronico', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('listasproductos', models.TextField(max_length=500)),
            ],
        ),
    ]
