# Generated by Django 5.1.2 on 2024-12-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idinventario', models.IntegerField(primary_key=True, serialize=False)),
                ('idempleado', models.IntegerField()),
                ('idcelular', models.IntegerField()),
                ('fecha_inventario', models.DateField()),
                ('cantidad_inventario', models.IntegerField()),
            ],
        ),
    ]
