# Generated by Django 5.1.2 on 2024-12-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='idinventario',
        ),
    ]
